name: Merge Code to Prod

on:
  push:
    branches:
      - DEV

jobs:
  merge_to_prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge code to PROD
      run: |
        git checkout remote/origin:PROD
        git merge DEV
