name: Create Pull Request

on:
  push:
    branches:
      - DEV

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v2
      with:
        ref: DEV
        repository: task
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Pull Request
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{
              "title": "Merge source_branch into target_branch",
              "head": "DEV",
              "base": "PROD",
              "body": "This pull request merges DEV into PROD."
            }' \
        https://api.github.com/repos/HakeemYB/task/pulls
