name: Merge Code to Prod

on:
  push:
    branches:
      - DEV

jobs:
  merge_to_prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "baighakeemyar.cloudlem@gmail.com"
        git config --global user.name "HakeemYB"

    - name: Merge code to PROD
      run: |
        git checkout -b origin/PROD
        git merge DEV
        git push origin PROD
